added deleverageAndWithdraw func
Instadapp/dsa-connectors pull request #229
Opened 2022-06-10 12:47 UTC by thrilok209

2022-06-10 21:00 UTC, pradyuman-verma commented
### Deployed on mainnet

[0x012fb8e5f1b111d202dcff12d350535320bfc5fad0f552248b472691aba79e4f](https://etherscan.io/tx/0x012fb8e5f1b111d202dcff12d350535320bfc5fad0f552248b472691aba79e4f)

2022-06-10 21:11 UTC, Vaibhav20201 requested changes, later dismissed

2022-06-10 21:11 UTC, Vaibhav20201 commented on contracts/mainnet/connectors/instaLite/main.sol
> +		require(getIds.length > 2, "invalid get-ids length");
```suggestion
		require(getIds.length >= 2, "invalid get-ids length");
```

2022-06-10 21:11 UTC, Vaibhav20201 commented on contracts/mainnet/connectors/instaLite/main.sol
> +		if (setIds.length > 2) {
```suggestion
		if (setIds.length >= 2) {
```

2022-06-10 21:11 UTC, Vaibhav20201 commented on contracts/mainnet/connectors/instaLite/main.sol
> +		uint256 _tokenAmt = tokenContract.balanceOf(address(this)) -
If its eth vault, we get eth and steth, not weth

2022-06-10 22:20 UTC, Vaibhav20201 commented
Deployed - [here](https://etherscan.io/address/0x3E5b9003e1674e15aA6a201b7B353C872C1ea791#code)

2022-06-11 12:54 UTC, pradyuman-verma approved these changes

2022-06-13 04:57 UTC, merged